#!/bin/sh
. "${dirname "$0"}/_/husky.sh"

echo 'Styling, testing and building your project before commiting';

# check prettier
npm run check-format ||
{
    echo 'Prettier check failed. Run npm run format, add changes and try commit again';
    false;
}

# check eslint
npm run check-lint || {
    echo 'Eslint check failed. Make the required changes listed above, add changes and try commit again';
    false;
}

# check ts config
npm run check-types || {
    echo 'Failed type check. Make the required changes listed above, add changes and try commit again';
    false;
}

npm run build || {
    echo 'Build failed, view the error above';
    false;
}

echo "success checking standard, ready to push";